export default {
    OPEN_ELEMENT: "BOTTOM_MENU.OPEN_ELEMENT",
    DELETE_ELEMENT: "BOTTOM_MENU.DELETE_ELEMENT",
    CLOSE_ELEMENT: "BOTTOM_MENU.CLOSE_ELEMENT",
    CHANGE_TAB: "BOTTOM_MENU.CHANGE_TAB"
};
