export default {
    ZOOM_SET: "WORKING_STAGE.ZOOM_SET",
    ZOOM_CHANGE: "WORKING_STAGE.ZOOM_CHANGE",
    OFFSET_CHANGE: "WORKING_STAGE.OFFSET_CHANGE",
    RESET_POSITION: "WORKING_STAGE.RESET_POSITION"
};
