export default {
    ZOOM_SET: "WORKING_STAGE.ZOOM_SET",
    ZOOM_CHANGE: "WORKING_STAGE.ZOOM_CHANGE",
    OFFSET_CHANGE: "WORKING_STAGE.OFFSET_CHANGE",
    RESET_POSITION: "WORKING_STAGE.RESET_POSITION",
    CREATE_UI_ELEMENT: "WORKING_STAGE.CREATE_UI_ELEMENT",
    CREATE_ELEMENT: "WORKING_STAGE.CREATE_ELEMENT",
    SHOW_ELEMENT: "WORKING_STAGE.SHOW_ELEMENT",
    DRAG_START: "WORKING_STAGE.DRAG_START",
    DRAG_MOVE: "WORKING_STAGE.DRAG_MOVE",
    DRAG_END: "WORKING_STAGE.DRAG_END",
    DELETE_ELEMENTS: "WORKING_STAGE.DELETE_FILES",
    ELEMENT_CLICK: "WORKING_STAGE.ELEMENT_CLICK",
    ELEMENT_POSITION_CHANGE: "WORKING_STAGE.ELEMENT_POSITION_CHANGE",
    ELEMENT_ANCHOR_CHANGE: "WORKING_STAGE.ELEMENT_ANCHOR_CHANGE",
    ELEMENT_SIZE_CHANGE: "WORKING_STAGE.ELEMENT_SIZE_CHANGE"
};
