export default {
    ADD_FILE: "PROJECT_DATA.ADD_FILE",
    ADD_DIRECTORY: "PROJECT_DATA.ADD_DIRECTORY",
    CHANGE_PROGRESS: "PROJECT_DATA.CHANGE_PROGRESS",
    CLEAR_LIBRARY: "PROJECT_DATA.CLEAR_LIBRARY"
};
