export default {
    SELECT_LIBRARY_ELEMENT: "PROPERTIES.SELECT_LIBRARY_ELEMENT",
    DELETE_LIBRARY_ELEMENT: "PROPERTIES.DELETE_LIBRARY_ELEMENT",
    RENAME_LIBRARY_ELEMENT: "PROPERTIES.RENAME_LIBRARY_ELEMENT"
};
