export default {
    TAB_ADD: "WORKING_AREA.TAB_ADD",
    TAB_SELECT: "WORKING_AREA.TAB_SELECT",
    TAB_CLOSE: "WORKING_AREA.SECTION_CLOSE",
    TRANSFORM_RESET: "WORKING_AREA.TRANSFORM_RESET",
    ZOOM_CHANGE: "WORKING_AREA.ZOOM_CHANGE"
};
